# Generated by Django 4.1.6 on 2023-06-15 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdf',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='pdf',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
